services:
  vectorstore:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ../../data/:/data/
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    entrypoint: "uvicorn vector_api:app --port 8001 --host 0.0.0.0"
    tty: true